name: Test installer

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test with Windows PowerShell 5.1
        shell: powershell
        run: ./tests/install.Tests.ps1
      - name: Test with PowerShell 7
        shell: pwsh
        run: ./tests/install.Tests.ps1
